FROM golang:1.13.8-alpine3.11 AS builder

RUN apk update && apk add git
WORKDIR /go/src/app
RUN go get -d -v github.com/gorilla/mux
COPY service.go .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o service .

FROM envoyproxy/envoy-alpine:v1.13.1

RUN apk update && apk add curl
RUN mkdir /code
COPY --from=builder /go/src/app/service /code/service
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
